- hosts: all
  become_method: sudo
  become_user: root
  connection: ssh
  become: yes

  vars:
    java_redhat_openjdk_packages:
        - java-11-openjdk-devel

  tasks:
    - name: install open jdk
      yum:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      when: ansible_distribution=="RedHat"
      loop:
        - "{{ java_redhat_openjdk_packages }}"
    - name: env lookup
      command: echo "{{ lookup('env','JOB_NAME') }}"
      register: envsvar
#    - name: find artifacts
#      find:
#        paths:
#          - /var/lib/jenkins/workspace/{{lookup('env','JOB_NAME')}}/
#        patterns:
#          - "*.jar"
#        file_type: file
#        recurse: no
#      register: jarfiles
    - name: copy mvn artifacts
      synchronize:
        src: /var/lib/jenkins/workspace/{{lookup('env','JOB_NAME')}}/target/*.jar
        dest: /files/
      when: ansible_distribution=="RedHat"
    - name: run java command
      shell: "java - jar /files/**/*.jar >> javarunoutputlogs.txt"
      when: ansible_distribution=="RedHat"


